- name: Download and install Kadalu
  shell: |
    curl -LO https://github.com/kadalu/kadalu/releases/latest/download/kubectl-kadalu
    chmod +x ./kubectl-kadalu
    mv ./kubectl-kadalu /usr/local/bin/kubectl-kadalu
    kubectl kadalu install
  when: setup_kadalu_operator
  
- name: Install and activate Ingress-Nginx
  shell: |
    helm upgrade --install ingress-nginx ingress-nginx \
    --repo https://kubernetes.github.io/ingress-nginx \
    --namespace ingress-nginx --create-namespace
  when: install_ingress_nginx